import React,{useEffect,useState}from'react';
import{adminApi}from'../../api/client';

export function AdminDashboard(){
 const[a,setA]=useState<any>(),[u,setU]=useState<any[]>([]),[amb,setAmb]=useState<any[]>([]),[l,setL]=useState<any[]>([]),[fac,setFac]=useState<any[]>([]),[roles,setRoles]=useState<any[]>([]),[tab,setTab]=useState<'users'|'rbac'|'ambulances'|'audit'>('users'),[busy,setBusy]=useState<string|null>(null);
 const load=()=>Promise.all([adminApi.getAnalytics(),adminApi.getUsers(),adminApi.getAmbulances(),adminApi.getAuditLog(50),adminApi.getHospitals(),adminApi.getRbacRoles()]).then(([x,y,z,w,f,r])=>{setA(x);setU(y);setAmb(z);setL(w);setFac(f);setRoles(r)});
 useEffect(()=>{load()},[]);
 const toggle=async(x:any)=>{setBusy(x.id);try{await adminApi.setUserActive(x.id,!x.is_active);await load()}finally{setBusy(null)}};
 const status=async(x:any)=>{setBusy(x.id);try{await adminApi.setAmbulanceStatus(x.id,x.status==='AVAILABLE'?'OFFLINE':'AVAILABLE');await load()}finally{setBusy(null)}};
 const assign=async(x:any,facility_id:string,facility_role:string)=>{setBusy(`rbac-${x.id}`);try{await adminApi.assignRbac(x.id,{facility_id:facility_id||null,facility_role:facility_role||null});await load()}finally{setBusy(null)}};
 return <div className="max-w-7xl mx-auto p-4 sm:p-6 space-y-6">
  <header><p className="text-xs font-bold text-emerald-700">SYSTEM ADMINISTRATION</p><h1 className="text-3xl font-black">MediKiosk Control Center</h1><p className="text-sm text-gray-500">Manage users, facility-scoped access, emergency fleet and audit activity.</p></header>
  <div className="grid grid-cols-2 lg:grid-cols-4 gap-3">{[['Users',a?.total_users,'👥'],['Active consultations',a?.active_consultations,'🩺'],['Available ambulances',a?.available_ambulances,'🚑'],['Critical alerts',a?.critical_alerts,'🚨']].map(x=><div key={x[0] as string} className="bg-white border border-emerald-100 rounded-2xl p-4 shadow-sm"><div>{x[2]}</div><p className="text-xs text-gray-500 mt-2">{x[0]}</p><p className="text-2xl font-black">{x[1]??0}</p></div>)}</div>
  <div className="bg-white border rounded-2xl overflow-hidden"><div className="flex overflow-x-auto border-b">
   {([['users','Users'],['rbac','Facility RBAC'],['ambulances','Ambulance fleet'],['audit','Audit log']] as const).map(([k,label])=><button key={k} onClick={()=>setTab(k)} className={`px-5 py-3 text-sm font-bold whitespace-nowrap ${tab===k?'text-emerald-700 border-b-2 border-emerald-600':''}`}>{label}</button>)}
  </div><div className="p-4">
   {tab==='users'&&<div className="space-y-2">{u.map(x=><div key={x.id} className="flex flex-wrap items-center justify-between gap-3 p-3 bg-gray-50 rounded-xl"><div><b className="text-sm">{x.full_name}</b><p className="text-xs text-gray-500">{x.email}</p><p className="text-[11px] text-gray-500 mt-1">Global role: {x.role} {x.facility_role&&` • ${x.facility_role}`} {x.facility_id&&` • ${fac.find(f=>f.id===x.facility_id)?.name||'facility'}`}</p></div><div className="flex items-center gap-2"><span className="text-[10px] font-bold bg-emerald-100 text-emerald-800 px-2 py-1 rounded-full">{x.role}</span><button disabled={busy===x.id} onClick={()=>toggle(x)} className={`text-xs font-bold px-3 py-1.5 rounded-lg ${x.is_active?'bg-red-50 text-red-700':'bg-emerald-600 text-white'}`}>{x.is_active?'Disable':'Enable'}</button></div></div>)}</div>}
   {tab==='rbac'&&<div className="space-y-4"><div className="rounded-2xl bg-emerald-50 border border-emerald-100 p-4"><h2 className="font-black text-emerald-950">Facility-based RBAC</h2><p className="text-sm text-emerald-900 mt-1">Assign a clinic/hospital and a facility role to each clinical or operations user. Their global role stays unchanged; this adds facility-scoped permissions for the demo admin.</p><p className="text-xs text-emerald-800 mt-2">Roles: Facility Admin, Doctor, Nurse, Reception, Dispatcher, Ambulance Coordinator, Viewer.</p></div>{u.filter(x=>x.role!=='PATIENT'&&x.role!=='ADMIN').map(x=><div key={x.id} className="border rounded-2xl p-4"><div className="mb-3"><b>{x.full_name}</b><p className="text-xs text-gray-500">{x.email} • global {x.role}</p></div><div className="grid sm:grid-cols-2 gap-3"><label className="text-xs font-bold text-gray-600">Clinic / Hospital<select value={x.facility_id||''} onChange={e=>assign(x,e.target.value,x.facility_role||'')} className="mt-1 w-full rounded-xl border-gray-200 bg-gray-50 px-3 py-2.5"><option value="">Unassigned</option>{fac.map(f=><option key={f.id} value={f.id}>{f.name} {f.is_government?'(Government)':'(Private)'}</option>)}</select></label><label className="text-xs font-bold text-gray-600">Facility role<select value={x.facility_role||''} onChange={e=>assign(x,x.facility_id||'',e.target.value)} className="mt-1 w-full rounded-xl border-gray-200 bg-gray-50 px-3 py-2.5"><option value="">No facility role</option>{roles.map(r=><option key={r.value} value={r.value}>{r.label}</option>)}</select></label></div>{busy===`rbac-${x.id}`&&<p className="text-xs text-emerald-700 mt-2">Saving access…</p>}</div>)}</div>}
   {tab==='ambulances'&&<div className="grid sm:grid-cols-2 gap-3">{amb.map(x=><div key={x.id} className="p-4 border rounded-2xl"><div className="flex justify-between"><b>{x.registration_number}</b><span className="text-xs font-bold">{x.status}</span></div><p className="text-xs text-gray-500 mt-1">{x.ambulance_type}</p><button disabled={busy===x.id} onClick={()=>status(x)} className="mt-3 text-xs font-bold text-emerald-700">{x.status==='AVAILABLE'?'Take offline':'Mark available'}</button></div>)}</div>}
   {tab==='audit'&&<div className="space-y-2 max-h-[500px] overflow-auto">{l.map(x=><div key={x.id} className="p-3 bg-gray-50 rounded-xl"><b className="text-xs">{x.action}</b><p className="text-[11px] text-gray-500">{x.entity_type||'system'} • {x.timestamp?new Date(x.timestamp).toLocaleString():''}</p></div>)}</div>}
  </div></div>
 </div>
}
